apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    nodePort: 30000  # You can specify a port within the 30000-32767 range
  selector:
    app: django-app
