apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todoapp-servicemonitor
  labels:
    release: prometheus
spec:
  endpoints:
  - path: /metrics
    port: http  # Ensure this matches the name of the port in the Service spec
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: todoapp
