apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todoapp-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: todoapp
  endpoints:
  - port: 8000
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
