name: CI/CD Pipeline for Todo Application

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the repository's code

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Set the Node.js version

      - name: Install dependencies
        run: npm install # Install application dependencies

      - name: Run tests
        run: npm test # Run tests

      - name: Build the application
        run: npm run build # Build the application (if needed)

  docker:
    runs-on: ubuntu-latest
    needs: build # Ensure the build job is completed before building the Docker image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }} # Your Docker Hub password

      - name: Build the Docker image
        run: |
          docker build . -t your-dockerhub-username/todo-app:latest # Build the Docker image
          
      - name: Push the Docker image
        run: |
          docker push your-dockerhub-username/todo-app:latest # Push the Docker image to Docker Hub
